default: &default
  adapter: postgresql
  encoding: utf8
  reconnect: true
  pool: 10
  host: 127.0.0.1

development:
  <<: *default
  database: oc_test_assignment_dev
  username:
  password:

test:
  <<: *default
  database: oc_test_assignment_test
  username:
  password: 
